# Generated by Django 2.0.2 on 2020-07-25 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_auto_20200724_1814'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomDetails',
            new_name='RoomCategoryDetails',
        ),
    ]
