# Generated by Django 2.0.2 on 2020-07-24 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20200724_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategory',
            name='roomsavailable',
            field=models.IntegerField(default=0),
        ),
    ]
