# Generated by Django 2.0.2 on 2020-08-07 12:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_roomcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategory',
            name='features',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
