# Generated by Django 2.0.2 on 2020-08-10 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_auto_20200810_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomcategorydetails',
            name='roomcategoryid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.RoomCategory'),
        ),
    ]
