# Generated by Django 2.0.2 on 2020-08-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('Other', 'Other')], default='male', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='guestname',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='totalpersons',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
