# Generated by Django 2.0.2 on 2020-08-19 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_auto_20200818_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='username',
            new_name='userid',
        ),
    ]
