# Generated by Django 2.0.2 on 2020-08-28 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_auto_20200828_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
