# Generated by Django 2.0.2 on 2020-09-03 13:17

from django.db import migrations, models
import hotel.models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0017_auto_20200828_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='secretkey',
            field=models.CharField(default=hotel.models.random_string, max_length=10),
        ),
    ]
