# Generated by Django 2.0.2 on 2020-09-04 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0018_profile_secretkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='secretkey',
        ),
    ]
